name: "Security Scan and Comment Action"
description: "Runs various open source security tools and then comments on PRs with results."
author: "Douglas Coburn"
runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  github_token:
    description: "GitHub token to post comments on PRs"
    required: true

  # Enable Settings
  python_sast_enabled:
    description: "Enable Python SAST analysis"
    required: false
    default: "false"

  golang_sast_enabled:
    description: "Enable Golang SAST analysis"
    required: false
    default: "false"

  javascript_sast_enabled:
    description: "Enable JavaScript SAST analysis"
    required: false
    default: "false"

  dockerfile_enabled:
    description: "Enable Dockerfile analysis"
    required: false
    default: "false"

  image_enabled:
    description: "Enable image scanning"
    required: false
    default: "false"

  secret_scanning_enabled:
    description: "Enable secret scanning"
    required: false
    default: "false"

  # Docker Configuration
  docker_images:
    description: "Comma-separated list of Docker images to scan"
    required: false
    default: ""
  dockerfiles:
    description: "Comma-separated list of Dockerfiles to scan"
    required: false
    default: ""

  # Trufflehog Configuration
  trufflehog_exclude_dir:
    description: "Comma-separated list of directories to exclude in Trufflehog"
    required: false
    default: ""
  trufflehog_rules:
    description: "Rules to enable in Trufflehog"
    required: false
    default: ""
  trufflehog_show_unverified:
    description: "Show unverified secrets in Trufflehog results"
    required: false
    default: "false"

  # Bandit Configuration
  bandit_exclude_dir:
    description: "Comma-separated list of directories to exclude in Bandit"
    required: false
    default: ""
  bandit_rules:
    description: "Rules to disable in Bandit"
    required: false
    default: ""

  # Gosec Configuration
  gosec_exclude_dir:
    description: "Comma-separated list of directories to exclude in Gosec"
    required: false
    default: ""
  gosec_rules:
    description: "Rules to enable in Gosec"
    required: false
    default: ""

  # Trivy Configuration
  trivy_exclude_dir:
    description: "Comma-separated list of directories to exclude in Trivy"
    required: false
    default: ""
  trivy_rules:
    description: "Rules to enable in Trivy"
    required: false
    default: ""

  # ESLint Configuration
  eslint_exclude_dir:
    description: "Comma-separated list of directories to exclude in ESLint"
    required: false
    default: ""
  eslint_rules:
    description: "Custom ESLint rules or plugins to enable"
    required: false
    default: ""

  # Log Forwarding Configuration
  sumo_logic_enabled:
    description: "Enable Sumo Logic log forwarding"
    required: false
    default: "false"
  sumo_logic_http_source_url:
    description: "HTTP source URL for Sumo Logic"
    required: false
    default: ""

  # Microsoft Sentinel Configuration
  ms_sentinel_enabled:
    description: "Enable Microsoft Sentinel log forwarding"
    required: false
    default: "false"
  ms_sentinel_workspace_id:
    description: "Workspace ID for Microsoft Sentinel"
    required: false
    default: "REPLACE_ME"
  ms_sentinel_shared_key:
    description: "Shared key for Microsoft Sentinel"
    required: false
    default: "REPLACE_ME"

  # Scan Scope Configuration
  scan_all:
    description: "If true, always scan the whole directory regardless of git or file list."
    required: false
    default: "false"
  scan_files:
    description: "Comma-separated list of files to scan. If not set, will use git diff or scan all."
    required: false
    default: ""

branding:
  icon: "shield"
  color: "blue"
